"""Create tables

Revision ID: 1d55ccf6a6c0
Revises: 
Create Date: 2022-07-09 17:14:00.121804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d55ccf6a6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('gbv',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ethicinity', sa.String(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('Id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('molest',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('ethicinity', sa.String(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('Id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molest')
    op.drop_table('gbv')
    op.drop_table('assist')
    # ### end Alembic commands ###
