"""Create tables

Revision ID: 1e936e3574cf
Revises: 
Create Date: 2022-07-11 13:08:25.205924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e936e3574cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username', 'email')
    )
    op.create_table('assist',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('gbv',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ethicinity', sa.String(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('Id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('molest',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('ethicinity', sa.String(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('Id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molest')
    op.drop_table('gbv')
    op.drop_table('assist')
    op.drop_table('admins')
    # ### end Alembic commands ###
